// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpcpvouyujctravabftj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwY3B2b3V5dWpjdHJhdmFiZnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1Njk2MTgsImV4cCI6MjA2MzE0NTYxOH0.xoBhtriw_qceyhKdnUYZZ6uX3sWXrkEyHBHOpS48XpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);